### ISSUE TITLE
Login Functionality

### ISSUE THREAD

**Issue by HStewart23** [fac-15/FAC-TRACK#17]
**User Story**
As a student I can choose to create an account or sign in.

**Acceptance Criteria**
- [ ] When I'm on FAC-TRAC I want to get an option to log-in or be able to navigate to a sign up page.
- [ ] Once signed up I want to be sent to a log-in page. 
- [ ] Once logged in I want to be sent straight to dashboard where I can see a header with a logo and a footer with navigation.
