### ISSUE TITLE
Dashboard- output data for a particular user

### ISSUE THREAD

**Issue by HStewart23** [fac-15/FAC-TRACK#19]
**User Story:**
 As a student I can easily see my tasks completed and aggregate confidence level for different weeks via an indicator on the dashboard.

**Acceptance Criteria:**

**dashboard**
- [x] I can easily see all subjects / weeks

**tasks**
- [x] I can see my progress shown as a fraction. 
- [x] I can see me progress shown visually as pie chart thing. 

**confidence**
- [x] I can see my aggregate confidence for a week displayed as a coloured bar on the dashboard.
- [x] The bar will always be the same length. 
- [x] The aggregation will be an average of the tasks for the week which have a confidence indicator filled in. 

---

![dashboard](https://user-images.githubusercontent.com/39189687/51118400-35a01780-1808-11e9-985d-020bda63fd83.png)
