### ISSUE TITLE
Show all weeks and tasks in UI

### ISSUE THREAD

**Issue by mr-bagglesworth** [fac-15/FAC-TRACK#32]
**Skateboard:** First Step, as recommended by the [Clio](https://hackmd.io/xMqgJEb8QRGaJ_uYD0eK1g#FAC-Track)

Relates to #44 , #33 
**Output dummy data to populate UI**
- [ ] query first user, get all talks, and empty values [#issue 33](https://github.com/fac-15/FAC-TRACK/issues/33)
- [ ] button links to weeks from dashboard (before charts)
- [ ] week view shows week name, and outputs dummy data for tasks
- [ ] task view shows task title and description
